/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "transport_MetaMessage.h"


#include <stdint.h>		// Use the C99 official header


void ccnxMetaMessage_Release1(CCNxMetaMessage *messagePtr) {
    ccnxMetaMessage_Release(&messagePtr);
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1CreateFromInterest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxInterest *arg1 = (CCNxInterest *) 0 ;
  CCNxMetaMessage *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxInterest **)&jarg1; 
  result = (CCNxMetaMessage *)ccnxMetaMessage_CreateFromInterest((CCNxInterest const *)arg1);
  *(CCNxMetaMessage **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1CreateFromContentObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  CCNxMetaMessage *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (CCNxMetaMessage *)ccnxMetaMessage_CreateFromContentObject((CCNxContentObject const *)arg1);
  *(CCNxMetaMessage **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1CreateFromControl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxControl *arg1 = (CCNxControl *) 0 ;
  CCNxMetaMessage *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxControl **)&jarg1; 
  result = (CCNxMetaMessage *)ccnxMetaMessage_CreateFromControl((CCNxControl const *)arg1);
  *(CCNxMetaMessage **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1CreateFromManifest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxManifest *arg1 = (CCNxManifest *) 0 ;
  CCNxMetaMessage *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxManifest **)&jarg1; 
  result = (CCNxMetaMessage *)ccnxMetaMessage_CreateFromManifest((CCNxManifest const *)arg1);
  *(CCNxMetaMessage **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1Display(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  arg2 = (int)jarg2; 
  ccnxMetaMessage_Display((CCNxTlvDictionary const *)arg1,arg2);
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1Acquire(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  CCNxMetaMessage *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (CCNxMetaMessage *)ccnxMetaMessage_Acquire((CCNxTlvDictionary const *)arg1);
  *(CCNxMetaMessage **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1IsInterest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (bool)ccnxMetaMessage_IsInterest((CCNxTlvDictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1IsInterestReturn(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (bool)ccnxMetaMessage_IsInterestReturn((CCNxTlvDictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1IsContentObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (bool)ccnxMetaMessage_IsContentObject((CCNxTlvDictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1IsControl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (bool)ccnxMetaMessage_IsControl((CCNxTlvDictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1IsManifest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (bool)ccnxMetaMessage_IsManifest((CCNxTlvDictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1Release(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CCNxMetaMessage **arg1 = (CCNxMetaMessage **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage ***)&jarg1; 
  ccnxMetaMessage_Release(arg1);
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1GetContentObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  CCNxContentObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (CCNxContentObject *)ccnxMetaMessage_GetContentObject((CCNxTlvDictionary const *)arg1);
  *(CCNxContentObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1GetInterest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  CCNxInterest *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (CCNxInterest *)ccnxMetaMessage_GetInterest((CCNxTlvDictionary const *)arg1);
  *(CCNxInterest **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1GetInterestReturn(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  CCNxInterest *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (CCNxInterest *)ccnxMetaMessage_GetInterestReturn((CCNxTlvDictionary const *)arg1);
  *(CCNxInterest **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1GetControl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  CCNxControl *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (CCNxControl *)ccnxMetaMessage_GetControl((CCNxTlvDictionary const *)arg1);
  *(CCNxControl **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1GetManifest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  CCNxManifest *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  result = (CCNxManifest *)ccnxMetaMessage_GetManifest((CCNxTlvDictionary const *)arg1);
  *(CCNxManifest **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1CreateFromWireFormatBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  CCNxMetaMessage *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (CCNxMetaMessage *)ccnxMetaMessage_CreateFromWireFormatBuffer(arg1);
  *(CCNxMetaMessage **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1CreateWireFormatBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  PARCSigner *arg2 = (PARCSigner *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  arg2 = *(PARCSigner **)&jarg2; 
  result = (PARCBuffer *)ccnxMetaMessage_CreateWireFormatBuffer(arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_transport_common_TransportMetaMessage_ccnxMetaMessage_1Release1(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CCNxMetaMessage *arg1 = (CCNxMetaMessage *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxMetaMessage **)&jarg1; 
  ccnxMetaMessage_Release1(arg1);
}


#ifdef __cplusplus
}
#endif

